name: Compile Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Configuring git environment.
         run: |
            git config --global user.name tejas101k
            git config --global user.email tejassingh649@rediffmail.com

       - name: Building Kernel.
         run: |
             git clone --depth 1 https://github.com/tejas101k/kernel_xiaomi_ginkgo.git -b fifteenKSU kernel
             cd kernel
             chmod 777 build.sh
             ./build.sh

       - name: Uploading ZIP.
         run: |
             cd kernel
             curl -fsSL -X POST https://api.telegram.org/bot7604080261:AAFINu3lPUAyaqj1iIFepdB3W/sendDocument -F chat_id=123456789 -F document=@"*.zip" -F caption="Kernel-4.9 For all device"  && echo ""
